### ISSUE TITLE
Centext Menu undefined

### ISSUE THREAD

**Issue by tarres** [MrElectroNick/cinnamon-applet-typescript#1]
Running the example (without modifying it) I get a weird error:
`this._applet_icon_box is undefined`
and
`this._applet_context_menu is undefined`
I'm running Cinnamon 3.4.1

**Comment by MrElectroNick** [comment]
@tarres Ohh... Not sure my last commit is functional as I stopped in the middle. I'll check and comment here

**Comment by MrElectroNick** [comment]
@tarres - Please try again. There was missing super._init call which is mandatory to properly init an applet

**Comment by tarres** [comment]
Seems to work, Thanks.
